### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by edson-acordi** [gwenhael-le-moine/x48ng#16]
Hi, gwenhael-le-moine, how are you?
I tried to compile it, and the result was:

a@Len-Y50-70:~/Downloads/x48ng-0.36.0$ sudo make install PREFIX=/usr DOCDIR=/usr/doc/x48ng MANDIR=/usr/man DESTDIR=/tmp/package

cc src/emu_serial.o src/emu_emulate.o src/emu_init.o src/emu_actions.o src/emu_memory.o src/emu_register.o src/emu_timer.o src/debugger.o src/runtime_options.o src/romio.o src/ui_text.o src/ui.o src/main.o src/ui_x11.o src/ui_sdl.o -o dist/x48ng -g -O2 -I./src/ -D_GNU_SOURCE=1 -DVERSION_MAJOR=0 -DVERSION_MINOR=36 -DPATCHLEVEL=0 -I/usr/include/lua5.4 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -D_GNU_SOURCE=1 -DHAS_X11=1 -D_GNU_SOURCE=1 -D_REENTRANT -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL -DHAS_SDL=1 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DNCURSES_WIDECHAR=1 -lm -llua5.4 -lreadline -lX11 -lXext -lSDL_gfx -lSDL -lncursesw -ltinfo
install -m 755 -d -- /tmp/package/usr/bin
install -c -m 755 dist/x48ng /tmp/package/usr/bin/x48ng
install -m 755 -d -- /tmp/package/usr/share/x48ng
install -c -m 755 dist/mkcard /tmp/package/usr/share/x48ng/mkcard
install -c -m 755 dist/dump2rom /tmp/package/usr/share/x48ng/dump2rom
install -c -m 755 dist/checkrom /tmp/package/usr/share/x48ng/checkrom
install -c -m 644 dist/hplogo.png /tmp/package/usr/share/x48ng/hplogo.png
cp -R dist/ROMs/ /tmp/package/usr/share/x48ng/
sed "s|@PREFIX@|/usr|g" dist/setup-x48ng-home.sh > /tmp/package/usr/share/x48ng/setup-x48ng-home.sh
chmod 755 /tmp/package/usr/share/x48ng/setup-x48ng-home.sh
install -m 755 -d -- /tmp/package/usr/man/man1
sed "s|@VERSION@|0.36.0|g" dist/x48ng.man.1 > /tmp/package/usr/man/man1/x48ng.1
gzip -9  /tmp/package/usr/man/man1/x48ng.1
install -m 755 -d -- /tmp/package/usr/doc/x48ng
cp -R AUTHORS LICENSE README* doc* romdump/ /tmp/package/usr/doc/x48ng
dist/x48ng --print-config > dist/config.lua
Lua error: (6) cannot open /root/.config/x48ng/config.lua: No such file or directory
There was an error reading /root/.config/x48ng/config.lua !
You can solve this by running `mkdir -p /root/.config/x48ng/ && x48ng --print-config >> /root/.config/x48ng/config.lua`

install -c -m 644 dist/config.lua /tmp/package/usr/doc/x48ng/config.lua
install -m 755 -d -- /tmp/package/usr/share/applications
sed "s|@PREFIX@|/usr|g" dist/x48ng.desktop > /tmp/package/usr/share/applications/x48ng.desktop

Note:
It was necessary to install these packages first:
libxext-dev
xorg-dev
x11proto-core-dev
x11proto-xext-dev
libsdl-gfx1.2-dev
libsdl1.2-compat-dev

OS: Ubuntu 22.04.3 LTS x86_64

**Comment by gwenhael-le-moine** [comment]
I'm fine, thank you for your report.

The error shown is actually benign and expected during `make install`.

The install script calls x48ng to generate the default config file. What's happening is `x48ng` tries to read the user's config file which doesn't exist, lua prints and error and x48ng also prints an additional message. Nonetheless it continues to run using its default config. 

Everything should run fine despite this error.

I've changed the message a bit for later versions, thanks.

**Comment by edson-acordi** [comment]
Thanks for your quick reply.
I can´t run the config file, or the x48ng after I trying to compile.

a@Len-Y50-70:~$ /usr/share/x48ng/setup-x48ng-home.sh
bash: /usr/share/x48ng/setup-x48ng-home.sh: No such file or directory

**Comment by edson-acordi** [comment]
I compiled it using,

sudo make install PREFIX=/usr

install -m 755 -d -- /usr/bin
install -c -m 755 dist/x48ng /usr/bin/x48ng
install -m 755 -d -- /usr/share/x48ng
install -c -m 755 dist/mkcard /usr/share/x48ng/mkcard
install -c -m 755 dist/dump2rom /usr/share/x48ng/dump2rom
install -c -m 755 dist/checkrom /usr/share/x48ng/checkrom
install -c -m 644 dist/hplogo.png /usr/share/x48ng/hplogo.png
cp -R dist/ROMs/ /usr/share/x48ng/
sed "s|@PREFIX@|/usr|g" dist/setup-x48ng-home.sh > /usr/share/x48ng/setup-x48ng-home.sh
chmod 755 /usr/share/x48ng/setup-x48ng-home.sh
install -m 755 -d -- /usr/man/man1
sed "s|@VERSION@|0.36.0|g" dist/x48ng.man.1 > /usr/man/man1/x48ng.1
gzip -9  /usr/man/man1/x48ng.1
install -m 755 -d -- /usr/doc/x48ng
cp -R AUTHORS LICENSE README* doc* romdump/ /usr/doc/x48ng
dist/x48ng --print-config > dist/config.lua
Lua error: (6) cannot open /root/.config/x48ng/config.lua: No such file or directory
There was an error reading /root/.config/x48ng/config.lua !
You can solve this by running `mkdir -p /root/.config/x48ng/ && x48ng --print-config >> /root/.config/x48ng/config.lua`

install -c -m 644 dist/config.lua /usr/doc/x48ng/config.lua
install -m 755 -d -- /usr/share/applications
sed "s|@PREFIX@|/usr|g" dist/x48ng.desktop > /usr/share/applications/x48ng.desktop

Now, it's working, thank you.

**Comment by gwenhael-le-moine** [comment]
Great! 

I updated the README as in fact none of the variables passed to make install are strictly necessary and as you found can be confusing.
