### ISSUE TITLE
Consider removing dist/ROMs/*rom*

### ISSUE THREAD

**Issue by antecrescent** [gwenhael-le-moine/x48ng#21]
Hi! The questionable legal status of the ROM files contained in the tarballs unfortunately makes it impossible to package this program for Gentoo (https://github.com/gentoo/guru/commit/a7332262e6df43cbfd99051c2d1e7b682dcbd8bb).

Would you consider removing them? Daring users would still be able to fetch them via `make get-roms`. I'm looking forward to hearing your thoughts on this.

**Comment by gwenhael-le-moine** [comment]
I had similar thoughts and you gave me a good reason to fix this.

I pushed this change to the `main` branch and it will be in the next release.

I moved the download of the ROMs into the `/usr/share/x48ng/setup-x48ng-home.sh` with an explanation and a chance to stop the process before the actual download. I hope this will be satisfactory for Gentoo inclusion.

Thank you.

**Comment by gwenhael-le-moine** [comment]
Part of release 0.38.0

**Comment by antecrescent** [comment]
>Part of release 0.38.0
>
Oh, sorry for the late reply! Yes, this is perfect, thanks.
