### ISSUE TITLE
Program fails to build with CFLAGS as command line arguments

### ISSUE THREAD

**Issue by antecrescent** [gwenhael-le-moine/x48ng#23]
249d50c44c7b5344841abbfcc6d16409546e514a breaks passing the `CFLAGS` as command line arguments, because they override all variable assignments in the Makefile, unless the `override` directive is used:

Reproduction
```
$ make CFLAGS="-O1" WITH_SDL=no WITH_X11=no
cc -O1   -c -o src/tools/mkcard.o src/tools/mkcard.c
[snip]
src/tools/checkrom.c:6:10: fatal error: romio.h: No such file or directory
    6 | #include "romio.h"
      |          ^~~~~~~~~
compilation terminated.
[snip]
```

Fix
e.g. https://github.com/gwenhael-le-moine/x48ng/pull/22

**Comment by gwenhael-le-moine** [comment]
Fixed by having merged #22
