### ISSUE TITLE
Uninstalling the old version to install the latest one

### ISSUE THREAD

**Issue by edson-acordi** [gwenhael-le-moine/x48ng#26]
Hi, gwenhael, how are you?
I have the v0.36 on my laptop.

I tried to uninstall it with,
sudo make uninstall x48ng

But it return,
make: *** No rule to make target 'uninstall'.  Stop.

When you release the next version, could you incorporate the rules into the code to provide a way to automatically uninstall it with make?

Thank you.

O.S.: Ubuntu 22.04.3
Kernel: 6.8.0-40-generic
Arch: x86_64

**Comment by gwenhael-le-moine** [comment]
Thanks for the suggestion, it'll be in the next release.
