### ISSUE TITLE
Segfault on initialization with SX ROM

### ISSUE THREAD

**Issue by seboss666** [gwenhael-le-moine/x48ng#5]
Hello,

First of all, thanks for keeping this software open to the world :) I'm trying to use the emulator, but I'm struggling to pass the first question at startup. I'm using [this little AUR package](https://aur.archlinux.org/packages/x48ng) on Manjaro. If it's of any use, here are some technical details:

- gcc 12.2.1
- readline 8.2.001
- libxext 1.3.5
- libx11 1.8.4
- 

When initializing manually :
```bash
$ x48ng -smallFont fixed -mediumFont fixed -largeFont fixed -connFont fixed -rom /usr/share/x48ng/ROMs/sxrom-j -initialize
using XShm extension.
Erreur de segmentation (core dumped)
```

I get the same result using the setup-x48ng-home.sh with modifying the rom name. Not sure if some specific setup is needed for the SX Rom to work correcly.

I'm not really used to tackle into C programs so I'm not sure what I could do to provide more detailed error messages (the "kernel" segfault message is not that useful also). I guess trying a debugger will be mandatory, any advice is welcome :)

Note that I tried the GX ROM and it works correctly, but as I have a HP48S at home I wanted to compare :)

**Comment by gwenhael-le-moine** [comment]
I can reproduce this here. To be honest I've never tried the SX roms before so I discover this too.

Even stranger is that the original x48 seem to have a similar bug. I can run `mkdir ~/.x48ng-sx && x48 -home ~/.x48ng-sx -rom /usr/share/x48ng/ROMs/sxrom-j -initialize` crashes too.

It looks like it may be a long-standing bug of x48. Still worth investigating and fixing

**Comment by MatMoul** [comment]
I just sent a PR for the SX ROMs #6 
There was an addressing error in hp48emu_memory.c.
I was able to test the changes with 2 128K cards with success.

**Comment by gwenhael-le-moine** [comment]
Awesome, thank you very much!
