### ISSUE TITLE
Possible to scale interface size?

### ISSUE THREAD

**Issue by bragostin** [gwenhael-le-moine/x48ng#9]
Thank you so much for publishing this! Reminds me of my student times, best calculator I ever had!
I have a 4K monitor and the interface is therefore quite small and difficult to use.
Do you think it is possible to either have a scaling option at startup or at compilation time?

**Comment by edson-acordi** [comment]
I use it on a monitor with HD resolution. Other than scaling it to greater than 100%, is there a way to implement scaling less than 100%?

**Comment by gwenhael-le-moine** [comment]
I'm wondering what's the best path here. On one hand I naively think introducing a scaling factor in the UI drawing code looks possible, although a moderately big task. On the other hand I think maybe writing a gtk4 (for example) GUI would be better in the long term.

Not sure where to go from there.

**Comment by bragostin** [comment]
@gwenhael-le-moine I first tried using `run_scaled` from https://github.com/kaueraal/run_scaled but it's crashing. It would be a simple solution though.

**Comment by gwenhael-le-moine** [comment]
@bragostin @edson-acordi After finding new energy I pushed many new version and the last one enables "resizability" of the UI (which is now sdl1). Resizing the window by hand scales the UI.

It's not yet a `--scale` option but I hope it helps.
